### ISSUE TITLE
Request support for markdown

### ISSUE THREAD

**Issue by xp12047** [desjarlais/Notepad-Light#17]
Looks like a nice piece of software and is small in size.  Can you add support for markdown syntax.  thanks

**Comment by desjarlais** [comment]
I will look into adding syntax support.

**Comment by xp12047** [comment]
> 我将考虑添加语法支持。

thank you

**Comment by desjarlais** [comment]
started working on adding markdown support using markdig:

https://github.com/xoofx/markdig

Once the work is done, I'll close out this comment and update the release notes

**Comment by desjarlais** [comment]
This feature will be included in 1.0.0.43, which is going to be released soon, probably by tomorrow 1/29/2023.  Still have a couple kinks to work on, but those can be bug fixes.  Displaying images for example does not currently work in the markdown viewer pane, but in general, it will render the markdown.
