### ISSUE TITLE
support MarkDown

### ISSUE THREAD

**Issue by FreeVB** [desjarlais/Notepad-Light#19]
Will you support MarkDown in the future?

**Comment by desjarlais** [comment]
I recently started to implement MarkDown in the latest version here -> https://github.com/desjarlais/Notepad-Light/releases/tag/v1.0.0.43

If you have any feedback about how it is implemented, please let me know how I can improve it.

**Comment by FreeVB** [comment]
Chinese is not supported: Chinese characters will display garbled code, and an error will occur when selecting all characters.

**Comment by desjarlais** [comment]
Can you provide some repro steps?  I think the Chinese characters not working is a product of the textbox I'm using, which is not Unicode based, it is ASCII based and that problem should be for markdown as well as other file formats.

**Comment by FreeVB** [comment]
When the batch is not in the MarkDown state, the Chinese display of garbled code is the same when the ordinary text file is opened.

An error occurs whenever you select text.

**Comment by desjarlais** [comment]
Do you have an example markdown file you can provide so that I can test the repro?

**Comment by FreeVB** [comment]
The second line is Chinese. Let's see if you can display it normally. When I open it, the display is garbled.
[README.md](https://github.com/desjarlais/Notepad-Light/files/10939611/README.md)

**Comment by desjarlais** [comment]
I do repro that, I'll take a look and see what is going on, more than likely this is a bug somewhere in my app.

**Comment by desjarlais** [comment]
can you try the latest version and see if it still reproduces?

https://github.com/desjarlais/Notepad-Light/releases/tag/v1.0.0.44

**Comment by FreeVB** [comment]
Thank you for your reply. The problem has been solved.

**Comment by desjarlais** [comment]
I can give it a try

**Comment by desjarlais** [comment]
I've added the synchronization of the scrollbar as a new feature request here:

https://github.com/desjarlais/Notepad-Light/issues/20

I'm glad the character issue is resolved, thank you for reporting it.  I will close this issue out, but if you have any other requests or questions, open another new issue and I'll do what I can to help out.
