### ISSUE TITLE
UTF-8 with BOM

### ISSUE THREAD

**Issue by FreeVB** [desjarlais/Notepad-Light#22]
If the file encoding is in UTF-8 format with BOM and is not supported when opened (displaying garbled code), is there a way to resolve this?

**Comment by desjarlais** [comment]
What kind of file are you using?  I tested a plain text file in UTF-8 with BOM and it did not display garbled text.  Are you using a markdown file in UTF8 with BOM?

**Comment by desjarlais** [comment]
Nevermind, I'm going to guess you are testing a markdown file because that does repro.  I'll fix that in the next release 1.0.0.46, sorry about that and thank you for reporting the behavior.

**Comment by desjarlais** [comment]
should be fixed in 1.0.0.46

https://github.com/desjarlais/Notepad-Light/releases/tag/v1.0.0.46
