### ISSUE TITLE
Major error--

### ISSUE THREAD

**Issue by FreeVB** [desjarlais/Notepad-Light#24]
Perhaps you modified something else? Opening any file now is garbled...

It's not just an MD file, it's garbled like opening a TXT file.

All English characters are also garbled.

**Comment by desjarlais** [comment]
Can you try the latest version and see if you still have the problem?

https://github.com/desjarlais/Notepad-Light/releases/tag/v1.0.0.48

**Comment by FreeVB** [comment]
Okay, everything is fine now.
